Integrated with QubeWire from KeySmith
qubecinema/wire-api pull request #1
Opened 2017-03-09 06:20 UTC by RajaBoseLeoM

##What does this PR contains?

1. Name changed from KeySmith to QubeWire.
2. Cleanup few changes in QubeWireClient and made it to work

2017-03-09 13:27 UTC, sivachandran requested changes

2017-03-09 13:27 UTC, sivachandran commented on README.txt
>      - Logging in and acquiring acess token
fix typo `acess`

2017-03-09 13:27 UTC, sivachandran commented on README.txt
> +QubeWireClient is a C++ application demonstrating QubeWire mastering APIs. It demonstrates the following functionalities of a mastering client.
`Qube Wire`, two words. Don't change the `QubeWireClient` as it is the program name.

2017-03-09 13:27 UTC, sivachandran commented on src/QubeWireClient.cpp
> +        // Make sure you maintain consistensy in QubeStoreClient::Impl() before making any changes
remove this comment

2017-03-09 13:27 UTC, sivachandran commented on src/QubeWireClient.cpp
> +#ifndef USE_STAGING
remove this macro

2017-03-09 13:27 UTC, sivachandran commented on src/QubeWireClient.cpp
> +            if (strstr(errorMessage.c_str(), "user denied access"))
simply return the error message

2017-03-09 13:27 UTC, sivachandran commented on src/QubeWireClient.cpp
> +        {
fix indentation

2017-03-09 13:27 UTC, sivachandran commented on src/QubeWireClient.h
> + * @author  Qube Dev <QubeDev@realimage.com>
remove this line

2017-03-09 13:27 UTC, sivachandran commented on src/QubeWireClient.h
> +     * (Privacy-enhanced Electronic Mail) form concatenated together
remove `(Privacy-enhanced Electronic Mail)`

2017-03-09 13:51 UTC, RajaBoseLeoM commented on src/QubeWireClient.h
> + * @author  Qube Dev <QubeDev@realimage.com>
I saw this line and thought its fine, but after seeing your comment it looks like its not fine to have an email address

2017-03-09 13:52 UTC, RajaBoseLeoM commented on src/QubeWireClient.cpp
> +#ifndef USE_STAGING
Searched and removed but missed this one

2017-03-10 01:33 UTC, sivachandran approved these changes

2017-03-18 11:50 UTC, merged